# Generated by Django 5.0.6 on 2026-04-01 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'is_deleted'], name='finance_fin_user_id_4b3314_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['transaction_type', 'date'], name='finance_fin_transac_b6d6df_idx'),
        ),
    ]
